version: "2.1"
services:
  register-ui:
    image: "huyinghuan/docker-register-frontend:v2"
    container_name: "private-registry-ui"
    environment:
      - ENV_DOCKER_REGISTRY_SERVER=http://172.28.210.141:5000
      - ENV_DOCKER_REGISTRY_UI_PORT=5001
      - ENV_DOCKER_REGISTRY_UI_AUTH=false
    ports:
      - "5001:5001"